"""websites table

Revision ID: 457117f5c83b
Revises: 60fd7ce70784
Create Date: 2018-08-15 18:13:04.258988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457117f5c83b'
down_revision = '60fd7ce70784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('url_hash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_last_update'), 'website', ['last_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_last_update'), table_name='website')
    op.drop_table('website')
    # ### end Alembic commands ###
